### ISSUE TITLE
No styles for nv-point-path from NPM package?

### ISSUE THREAD

**Issue by ttrmw** [novus/nvd3#1401]
Hey, I'm using nvd3 via the NPM package and it looks like nvd3's stylesheets might be missing? I'm getting huge black blobs over points on my line graph, and setting:

```css
.nv-point-path { 
  display: none;
}
```
fixes the issue. I'm guessing there ought to be some style set against this class?
