### ISSUE TITLE
How to get rid of grid lines?

### ISSUE THREAD

**Issue by togakangaroo** [novus/nvd3#59]
Not really an issue, but lacking a forum, irc, email, faq, or wiki got to ask here - how on earth do you get rid of the grid lines behind the charts?

I can't even find where in the code they're coming from.

**Comment by bobbyziom** [comment]
```css
.nvd3.nv-lineChart .nv-x.nv-axis line { stroke: none; fill: none; }
.nvd3.nv-lineChart .nv-y.nv-axis line { stroke: none; fill: none; }
```
worked for me
