### ISSUE TITLE
CSS colors

### ISSUE THREAD

**Issue by pvinchon** [novus/nvd3#60]
Hi, 

I removed most inline CSS and added a nv-color- i class to the legend, the tool tips and the lines / bars / areas. My changes work, but are quite messy.

Are you going to release any similar feature to remove CSS from JS files ?

**Comment by smudge** [comment]
For anyone stumbling across this issue via Google, adding `!important` to CSS will allow you to override the inline styles added by nvd3. This should resolve the issue in most cases. Like so:

```css
.nv-series-0 { stroke: #6BB9F0 !important; fill: #6BB9F0 !important }
.nv-series-1 { stroke: #4183D7 !important; fill: #4183D7 !important }
/* ... */
```

I ran into this because I needed to change a chart's color scheme based on the color of the container it was in, and it was FAR, FAR easier to do this using CSS (colors are just scoped under class names). 

The alternative--of manually telling the javascript what colors to use when initializing a chart--is unacceptable, IMO, especially when you have multiple color schemes on the same page. Using inline styles isn't actually easier if you actually want to separate your presentation from your content, and I find it concerning how quickly this issue was dismissed.
